#!/usr/bin/env bash

function main() {
  local commit_message_file="$1"

  local is_amend_command
  is_amend_command="$(ps -ocommand= -p $PPID | grep -e '--amend')"

  if [[ -n "$is_amend_command" ]]; then
    exit 0
  fi

  local branch
  branch="$(git rev-parse --abbrev-ref HEAD)"

  [[ "$branch" =~ ^([a-z]+)/([A-Z]+-[0-9]+)-([a-zA-Z0-9-]+) ]]

  local classification
  classification="${BASH_REMATCH[1]}"
  local ticket_id
  ticket_id="${BASH_REMATCH[2]}"
  local commit_message
  commit_message=$(echo "${BASH_REMATCH[3]}" | tr '-' ' ')

  if [[ -z "$classification" || -z "$ticket_id" ]]; then
    exit 0
  fi

  declare classification_abbreviation

  case "$classification" in
  "feature")
    classification_abbreviation="F"
    ;;
  "bugfix")
    classification_abbreviation="B"
    ;;
  *)
    classification_abbreviation="C"
    ;;
  esac

  echo "[$classification_abbreviation] $ticket_id: $commit_message" >"$commit_message_file"
}

main "$@"
